#!/usr/bin/env rake
require 'rake' unless defined?(Rake)

task :default => [:ext_build]
task :ext_build => [:ext_clean, :ext_make]

task :ext_clean do
  Dir.glob("./*.o").each{|x| sh "rm #{x}"}
  sh("rm ktools.bundle"){|x, y| true}
end

task :ext_make do
  files = []
  Dir.glob("./*.c").each{|x| sh "gcc -O2 -pipe -fno-common -DHAVE_KQUEUE -c #{x}"; files << x.gsub(/\.c/, ".o")}
  sh "cc -dynamic -bundle -undefined suppress -flat_namespace -o ktools.bundle #{files.join(' ')}"
end